apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hpa
spec:
  #replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tknika-hpa
  template:
    metadata:
      labels:
        app: tknika-hpa
    spec:
      containers:
        - name: lehenengonginx
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            #limits:
            #  cpu: 200m
            #  memory: 256Mi