apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdeployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: tknika-nginx
  template:
    metadata:
      labels:
        app: tknika-nginx
    spec:
      containers:
        - name: lehenengonginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: bolumena
        - name: contenido
          image: ubuntu
          command: ["/bin/sh"]
          args: ["-c", "echo Kaixo Tknikatik > /data/index.html && tail -f /dev/null"]
          volumeMounts:
            - mountPath: /data
              name: bolumena
      volumes:
        - name: bolumena
          emptyDir: {}
